# Generated by Django 4.1.7 on 2023-03-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='templates/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, upload_to='templates/products/large/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, upload_to='templates/products/medium/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, upload_to='templates/products/small/'),
        ),
    ]
